name: cf_poke_datsu_data
description: "A Dart library for PokeAPI"
publish_to: "none"
version: 0.0.1

environment:
  sdk: 3.4.4

dependencies:
  dio: 5.5.0+1
  equatable: 2.0.5

dev_dependencies:
  build_runner: 2.4.11
  build_test: ^2.2.2
  lints: ^4.0.0
  test: '>=1.15.0 <2.0.0'
